// import { IVpcNetworkData } from '@/_core/entities/networking/vpc/types'
//
// export const mockVpcNetworkData: IVpcNetworkData[] = [
//   {
//     id: 'vpc-001',
//     name: 'Test VPC 1',
//     status: 'ACTIVE',
//     subnets: ['subnet-001', 'subnet-002'],
//     shared: false,
//     availability_zone_hints: ['zone-1', 'zone-2'],
//     availability_zones: ['zone-1', 'zone-2'],
//     ipv4_address_scope: 'scope-1',
//     ipv6_address_scope: 'scope-2',
//     router_external: true,
//     description: 'This is a test VPC network 1',
//     port_security_enabled: true,
//     qos_policy_id: 'qos-001',
//     l2_adjacency: false,
//     tags: ['tag1', 'tag2'],
//     created_at: '2025-04-16T01:46:01.222Z',
//     updated_at: '2025-04-16T01:46:01.222Z',
//     revision_number: 1,
//     provider_network_type: 'vxlan',
//     provider_physical_network: 'physnet1',
//     provider_segmentation_id: 1001,
//   },
//   {
//     id: 'vpc-002',
//     name: 'Test VPC 2',
//     status: 'DOWN',
//     subnets: ['subnet-003'],
//     shared: true,
//     availability_zone_hints: [],
//     availability_zones: ['zone-3'],
//     ipv4_address_scope: 'scope-3',
//     ipv6_address_scope: '',
//     router_external: false,
//     description: 'This is a test VPC network 2',
//     port_security_enabled: false,
//     qos_policy_id: 'qos-002',
//     l2_adjacency: true,
//     tags: ['tag3'],
//     created_at: '2025-04-16T01:46:01.222Z',
//     updated_at: '2025-04-16T01:46:01.222Z',
//     revision_number: 2,
//     provider_network_type: 'gre',
//     provider_physical_network: 'physnet2',
//     provider_segmentation_id: 1002,
//   },
//   {
//     id: 'vpc-003',
//     name: 'Test VPC 3',
//     status: 'BUILD',
//     subnets: [],
//     shared: false,
//     availability_zone_hints: ['zone-4'],
//     availability_zones: ['zone-4', 'zone-5'],
//     ipv4_address_scope: '',
//     ipv6_address_scope: 'scope-4',
//     router_external: true,
//     description: 'This is a test VPC network 3',
//     port_security_enabled: true,
//     qos_policy_id: '',
//     l2_adjacency: false,
//     tags: ['tag4', 'tag5'],
//     created_at: '2023-03-01T12:00:00Z',
//     updated_at: '2023-03-02T12:00:00Z',
//     revision_number: 3,
//     provider_network_type: 'flat',
//     provider_physical_network: 'physnet3',
//     provider_segmentation_id: 1003,
//   },
// ]
